### ISSUE TITLE
Could you provide the minified file?

### ISSUE THREAD

**Issue by kennynaoh** [just-animate/just-animate#18]
Hello @notoriousb1t ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
Could you provide the minified file for `just-animate-systemjs.js` on [npm](https://www.npmjs.com/package/just-animate)?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8336
https://github.com/cdnjs/cdnjs/pull/8344

**Comment by notoriousb1t** [comment]
Yes. I should be able to publish with a min in a few hours from now.

**Comment by notoriousb1t** [comment]
@kennynaoh If you point to 0.6.1, it should now have a minified systemjs file.

**Comment by kennynaoh** [comment]
@notoriousb1t , thanks for your help!
