### ISSUE TITLE
module not found when using typescript import the web module.

### ISSUE THREAD

**Issue by tedwong** [just-animate/just-animate#45]
Here is how I import the web module:

> `import { waapiPlugin } from 'just-animate/web';
`

![image](https://user-images.githubusercontent.com/188722/32154245-5bfafc78-bd6a-11e7-9b5e-1326f645192e.png)
Did I do something wrong?

**Comment by notoriousb1t** [comment]
The docs are a little out of date.  It should be 

```ts
import { waapiPlugin } from 'just-animate/lib/web';
import { addPlugin } from 'just-animate';
addPlugin(waapiPlugin);
```

The paths had to be moved down to just-animate/lib/web to accommodate tree-shaking.
