### ISSUE TITLE
[question] React support / integration?

### ISSUE THREAD

**Issue by t47io** [just-animate/just-animate#46]
I think it might take something like https://github.com/bringking/react-web-animation in order to use this library with React?

**Comment by notoriousb1t** [comment]
Here is a simple example of using just-animate with react: https://codepen.io/notoriousb1t/pen/rpdyMB/?editors=0010

The strategy for React, Vue, and Angular is pretty similar.  On mount get the reference to the node and do setup and on unmount, do teardown.  For appear/leave logic in React, wrapping the element in TransitionGroup provides the necessary hooks to play animations during each of those states. 

I'm not opposed to writing framework specific integrations, but I am not sure at this point if it would be that helpful.
