### ISSUE TITLE
[question] is WAAPI required?

### ISSUE THREAD

**Issue by t47io** [just-animate/just-animate#47]
I read from https://just-animate.github.io/basic-usage/

> This guide assumes the web plugin (Web Animations API) is installed.

Just want to confirm that in order to have `just-animate` work, WAAPI is required. In other words, a WAAPI polyfill is probably needed in production for all users.

**Comment by notoriousb1t** [comment]
Yes and no.

It depends on what is being animated.  For "props" (css variables, attributes, and object properties), you don't need even need the just-animate web plugin.  So for instance, using just-animate with ThreeJS, PixiJS, Polymorph, .etc does not require the web plugin.

To animate HTMLElement styles through "web", you need the web plugin and that depends on WAAPI.  Edge/Safari do not have support, so the best option at the moment is to include the official plugin.
 
However, the intent of that particular disclaimer is to say that everything on this docs page assumes just-animate-web is loaded.

**Comment by t47io** [comment]
OK thank you for the answer. I now see it mentioned in https://just-animate.github.io/property-options/. I was only thinking about DOM use cases and didn't thought about the others. Anyway, it might be good to clarify such in the docs in a more visible way.

**Comment by notoriousb1t** [comment]
Will do. I’ll revisit the language to make it clearer. 😀
