### ISSUE TITLE
Rotation about center of element

### ISSUE THREAD

**Issue by TimeTravel-1** [just-animate/just-animate#54]
I want to rotate around the center of an svg element. So when I say rotate: 30, I want it to rotate around the center of the svg element instead of around the container. How would I accomplish this? There is another animation library out there that allows thisas default http://thednp.github.io/kute.js/svg.html, but I want to use solely this one. Thanks.

**Comment by notoriousb1t** [comment]
Can you provide a small example on codepen or a playground of what you are trying to do?

**Comment by TimeTravel-1** [comment]
Thanks for the quick reply. For instance, making a line rotate 30 degrees about its own center. If I use just-animate, it rotates about 0,0 I think.  [https://codepen.io/TimeTravel_1/pen/YggqOo]

**Comment by notoriousb1t** [comment]
SVG transforms are kind of messy and have inconsistent browser support. While SVG animations aren't the primary focus of Just Animate, the "props" animations can be adapted for any target including SVG lines and paths.

I created the following example showing how to do advanced animations with props and also an example that shows how to set transform-origin on the line/path using the web animations api "web" animations: https://codepen.io/notoriousb1t/pen/oVRwYJ The props example requires just-animate version 2.6.2

**Comment by TimeTravel-1** [comment]
Thanks for the help. The props solution seems consistent between Safari and Chrome, while the web animations solution doesn't work the same. Thanks for the advice.
